"""
Tests for configuration management.
"""

import pytest
from src.viafoundry_mcp.config import (
    get_credentials,
    set_credentials,
    validate_credentials,
    resolve_hostname,
    is_localhost_request,
    build_hostname_from_request,
    LOCALHOST_HOSTS,
)


@pytest.fixture(autouse=True)
def reset_credentials():
    """Reset credentials before and after each test."""
    set_credentials(None, None)
    yield
    set_credentials(None, None)


def test_set_and_get_credentials():
    """Test setting and getting credentials from context."""
    set_credentials("https://viafoundry.com", "via_mcp_my-token")
    hostname, token = get_credentials()
    
    assert hostname == "https://viafoundry.com"
    assert token == "via_mcp_my-token"


def test_get_credentials_default_none():
    """Test that credentials default to None."""
    hostname, token = get_credentials()
    
    assert hostname is None
    assert token is None


def test_validate_credentials_valid():
    """Test validation of valid credentials."""
    assert validate_credentials(
        "https://viafoundry.com",
        "via_mcp_valid-token"
    ) is True


def test_validate_credentials_valid_http():
    """Test validation accepts http:// hostname."""
    assert validate_credentials(
        "http://localhost:8080",
        "via_mcp_valid-token"
    ) is True


def test_validate_credentials_missing_hostname():
    """Test validation fails with missing hostname."""
    assert validate_credentials("", "via_mcp_token") is False
    assert validate_credentials(None, "via_mcp_token") is False


def test_validate_credentials_missing_token():
    """Test validation fails with missing token."""
    assert validate_credentials("https://viafoundry.com", "") is False
    assert validate_credentials("https://viafoundry.com", None) is False


def test_validate_credentials_invalid_hostname():
    """Test validation fails with invalid hostname format."""
    assert validate_credentials("viafoundry.com", "via_mcp_token") is False
    assert validate_credentials("ftp://viafoundry.com", "via_mcp_token") is False


def test_validate_credentials_empty_host():
    """Test validation fails with empty host (just protocol)."""
    # These could be generated by build_hostname_from_request with empty host
    assert validate_credentials("https://", "via_mcp_token") is False
    assert validate_credentials("http://", "via_mcp_token") is False
    assert validate_credentials("https:///beta", "via_mcp_token") is False  # Empty host with path


def test_validate_credentials_invalid_token_prefix():
    """Test validation fails with invalid token prefix."""
    assert validate_credentials("https://viafoundry.com", "invalid-token") is False
    assert validate_credentials("https://viafoundry.com", "mcp_token") is False


def test_credentials_are_context_scoped():
    """Test that credentials are stored in context variables."""
    # Set credentials
    set_credentials("https://test.com", "via_mcp_test-token")
    
    # Verify they persist
    hostname1, token1 = get_credentials()
    hostname2, token2 = get_credentials()
    
    assert hostname1 == hostname2 == "https://test.com"
    assert token1 == token2 == "via_mcp_test-token"


def test_credentials_can_be_overwritten():
    """Test that credentials can be updated."""
    set_credentials("https://first.com", "via_mcp_first-token")
    hostname1, token1 = get_credentials()
    
    set_credentials("https://second.com", "via_mcp_second-token")
    hostname2, token2 = get_credentials()
    
    assert hostname1 == "https://first.com"
    assert token1 == "via_mcp_first-token"
    assert hostname2 == "https://second.com"
    assert token2 == "via_mcp_second-token"


# ============================================================================
# Localhost Detection Tests
# ============================================================================

class TestIsLocalhostRequest:
    """Tests for localhost detection."""
    
    def test_localhost_hosts_detected(self):
        """Test that all localhost hosts are detected."""
        for host in LOCALHOST_HOSTS:
            assert is_localhost_request(host) is True, f"{host} should be localhost"
    
    def test_localhost_with_port_detected(self):
        """Test that localhost with port is detected."""
        assert is_localhost_request("127.0.0.1:8000") is True
        assert is_localhost_request("localhost:8000") is True
        assert is_localhost_request("0.0.0.0:8000") is True
    
    def test_production_hosts_not_localhost(self):
        """Test that production hosts are not localhost."""
        production_hosts = [
            "viafoundry.com",
            "mcp.viafoundry.com",
            "192.168.1.1",
            "10.0.0.1:8000",
            "example.com:443",
        ]
        for host in production_hosts:
            assert is_localhost_request(host) is False, f"{host} should not be localhost"
    
    def test_empty_host_not_localhost(self):
        """Test that empty host is not localhost."""
        assert is_localhost_request("") is False
        assert is_localhost_request(None) is False


class TestBuildHostnameFromRequest:
    """Tests for hostname building (with /mcp suffix trimmed)."""
    
    def test_build_hostname_strips_mcp(self):
        """Test that /mcp suffix is stripped."""
        url = build_hostname_from_request("https", "example.com", "/mcp")
        assert url == "https://example.com"
    
    def test_build_hostname_keeps_prefix_path(self):
        """Test that prefix path before /mcp is kept."""
        url = build_hostname_from_request("https", "example.com", "/beta/mcp")
        assert url == "https://example.com/beta"
    
    def test_build_hostname_complex_path(self):
        """Test with more complex path prefix."""
        url = build_hostname_from_request("https", "dev-playground.infra.gcp.viafoundry.net", "/beta/mcp")
        assert url == "https://dev-playground.infra.gcp.viafoundry.net/beta"
    
    def test_build_hostname_no_path(self):
        """Test with no path."""
        url = build_hostname_from_request("https", "example.com")
        assert url == "https://example.com"
    
    def test_build_hostname_with_port(self):
        """Test building hostname with port."""
        url = build_hostname_from_request("http", "localhost:8000", "/mcp")
        assert url == "http://localhost:8000"
    
    def test_build_hostname_non_mcp_path(self):
        """Test that non-mcp paths are kept as-is."""
        url = build_hostname_from_request("https", "example.com", "/api/v1")
        assert url == "https://example.com/api/v1"


# ============================================================================
# Hostname Resolution Tests
# ============================================================================

class TestResolveHostname:
    """Tests for hostname resolution based on request URL."""
    
    def test_localhost_allows_custom_header(self):
        """Localhost requests allow any X-ViaFoundry-Hostname value."""
        hostname, is_localhost = resolve_hostname(
            header_hostname="https://custom.viafoundry.com",
            request_scheme="http",
            request_host="127.0.0.1:8000",
            request_path="/mcp"
        )
        assert hostname == "https://custom.viafoundry.com"
        assert is_localhost is True
    
    def test_localhost_returns_none_without_header(self):
        """Localhost requests return None if no header provided."""
        hostname, is_localhost = resolve_hostname(
            header_hostname=None,
            request_scheme="http",
            request_host="localhost:8000",
            request_path="/mcp"
        )
        assert hostname is None
        assert is_localhost is True
    
    def test_production_strips_mcp_suffix(self):
        """Production requests strip /mcp suffix from hostname."""
        hostname, is_localhost = resolve_hostname(
            header_hostname="https://custom.viafoundry.com",  # Should be ignored
            request_scheme="https",
            request_host="mcp.viafoundry.com",
            request_path="/mcp"
        )
        assert hostname == "https://mcp.viafoundry.com"
        assert is_localhost is False
    
    def test_production_keeps_prefix_path(self):
        """Production requests keep path prefix before /mcp."""
        hostname, is_localhost = resolve_hostname(
            header_hostname="https://custom.viafoundry.com",  # Should be ignored
            request_scheme="https",
            request_host="dev-playground.infra.gcp.viafoundry.net",
            request_path="/beta/mcp"
        )
        assert hostname == "https://dev-playground.infra.gcp.viafoundry.net/beta"
        assert is_localhost is False
    
    def test_production_ignores_header(self):
        """Production requests ignore X-ViaFoundry-Hostname header."""
        hostname, is_localhost = resolve_hostname(
            header_hostname="https://malicious.site.com",  # Must be ignored
            request_scheme="https",
            request_host="prod.viafoundry.com",
            request_path="/mcp"
        )
        assert hostname == "https://prod.viafoundry.com"
        assert is_localhost is False
    
    def test_production_works_without_header(self):
        """Production requests work without header."""
        hostname, is_localhost = resolve_hostname(
            header_hostname=None,
            request_scheme="https",
            request_host="prod.viafoundry.com",
            request_path="/mcp"
        )
        assert hostname == "https://prod.viafoundry.com"
        assert is_localhost is False
    
    def test_localhost_with_port(self):
        """Localhost with port should work."""
        hostname, is_localhost = resolve_hostname(
            header_hostname="https://my-viafoundry.com",
            request_scheme="http",
            request_host="0.0.0.0:8000",
            request_path="/mcp"
        )
        assert hostname == "https://my-viafoundry.com"
        assert is_localhost is True
    
    def test_production_preserves_port(self):
        """Production hostname preserves port if present."""
        hostname, is_localhost = resolve_hostname(
            header_hostname=None,
            request_scheme="https",
            request_host="prod.viafoundry.com:8443",
            request_path="/mcp"
        )
        assert hostname == "https://prod.viafoundry.com:8443"
        assert is_localhost is False
